apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: xo-connect5
  labels:
    name: debug
spec:
  containers:
    - name: redis-cli
      image: "redis:7.0.4"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: busybox
      image: gcr.io/google-containers/busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      tty: true
