apiVersion: v1
kind: Pod
metadata:
  name: xo-redis-pod
  namespace: xo-connect5
  labels:
    name: xo-redis-pod
spec:
  containers:
    - name: xo-redis-container
      image: "redis:7.0.4"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/data"
          name: xo-redis-data
      ports:
        - containerPort: 6379
  volumes:
    - name: xo-redis-data
      emptyDir: {}
